### ISSUE TITLE
Customise webpack

### ISSUE THREAD

**Issue by stephencookdev** [onfido/pinion-pipeline#4]
Currently there are no real hooks into webpack

This means that several things are entirely impossible, such as adding in custom webpack plugins, or custom loaders

There should be some API exposed to allow webpack customisation, referencing the target `node_modules` directory to get the plugins/loaders

**Comment by fritx** [comment]
Try this:

```js
// webpack.config.js

// node_modules
// - tls-connect
// - workerjs
// node_modules_custom
// - my-hacked-module

// hack modulePaths at runtime
// set NODE_PATH and re-initPaths
const delimiter = require('path').delimiter
let nodePath = 'node_modules_custom'
if (process.env.NODE_PATH) {
  nodePath += delimiter + process.env.NODE_PATH
}
process.env.NODE_PATH = nodePath
require('module')._initPaths()
////

module.exports = {
  resolve: {
    root: [
      join(__dirname, 'node_modules'),
      join(__dirname, 'node_modules_custom'),
    ],
}
```

**Comment by stephencookdev** [comment]
Thanks @fritx - I've done something similar in https://github.com/onfido/pinion-pipeline/pull/6

This should allow us to specify custom loaders. Custom plugins I want to hold off until v2 of Pinion, which should inherently offer more power to customise tasks.
